# Generated by Django 4.1.4 on 2022-12-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='code_lang',
            field=models.CharField(default='text', max_length=32),
        ),
    ]
